name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t your-docker-username/your-repo-name:latest \
            -t your-docker-username/your-repo-name:${{ github.sha }} \
            .
          docker push your-docker-username/your-repo-name:latest
          docker push your-docker-username/your-repo-name:${{ github.sha }}
        env:
          DOCKER_CLI_ACI=0
          DOCKER_BUILDKIT=1
